/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server.swing;

/**
 *
 * @author pungin
 */
public class Progressbar extends javax.swing.JFrame {

    public static final Progressbar instance = new Progressbar();
    private int steps = 1;
    private int step = 1;
    private String title = "";
    private int value = 0;
    private int maximum = 100;
    private int minimum = 0;
    private String text = "";

    /**
     * Creates new form Progressbar
     */
    public Progressbar() {
        steps = 1;
        step = 1;
        title = "";
        value = 0;
        maximum = 100;
        minimum = 0;
        text = "";
        initComponents();
    }

    @Override
    public void setVisible(boolean bln) {
        if (bln) {
            setLocationRelativeTo(null);
        }
        super.setVisible(bln);
        if (!bln) {
            init();
        }
    }

    private void init() {
        setTitle("", 1);
        setStep(1);
        setText("");
        setMaximum(100);
        setMinimum(0);
        setValue(0);
    }

    @Override
    public String getTitle() {
        return title;
    }

    @Override
    public void setTitle(String str) {
        title = str;
        if (steps > 1) {
            str += "(" + step + "/" + steps + ")";
        }
        super.setTitle(str);
    }

    public static void visible(boolean bln) {
        instance.setVisible(bln);
    }

    public static void updateTitle(String str) {
        instance.setTitle(str);
    }

    public static void setTitle(String str, int steps) {
        setSteps(steps);
        instance.setTitle(str);
    }

    public static void setSteps(int steps) {
        instance.steps = steps;
        instance.setTitle(instance.title);
    }

    public static void nextStep() {
        setStep(++instance.step);
    }

    public static void setStep(int step) {
        instance.step = step;
        instance.setTitle(instance.title);
    }

    public static void updateText() {
        setText(instance.text);
    }

    public static void setText(String str) {
        instance.text = str;
        instance.jLabel1.setText(instance.text + (getPercent() > -1 ? ("(" + getPercent() + "%)") : ""));
    }

    public static int getPercent() {
        if (instance.maximum <= 0) {
            return -1;
        }
        return (instance.value - instance.minimum) * 100 / instance.maximum;
    }

    public static void addValue() {
        setValue(++instance.value);
    }

    public static void setValue(int i) {
        instance.value = Math.max(Math.min(i, instance.maximum), instance.minimum);
        instance.jProgressBar1.setValue(instance.value);
        updateText();
    }

    public static int getValue() {
        return instance.value;
    }

    public static void setMaximum(int i) {
        instance.maximum = i;
        instance.jProgressBar1.setMaximum(instance.maximum);
    }

    public static void setMinimum(int i) {
        instance.minimum = i;
        instance.jProgressBar1.setMinimum(instance.minimum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        AppIcon = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        AppIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon.png"))); // NOI18N
        AppIcon.setText("jLabel56");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, AppIcon,
                org.jdesktop.beansbinding.ELProperty.create("${icon.image}"), this,
                org.jdesktop.beansbinding.BeanProperty.create("iconImage"));
        bindingGroup.addBinding(binding);

        jProgressBar1.setBorderPainted(false);

        jLabel1.setText("正在加載...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup().addComponent(jLabel1).addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap(11, Short.MAX_VALUE).addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jProgressBar1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap()));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
     // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JLabel AppIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
